### ISSUE TITLE
Hide only in public side

### ISSUE THREAD

**Issue by alfonsomontejo** [zerocrates/HideProperties#3]
Hi. It would be good if the module allowed to select if the hiding of the fields was restricted exclusively to the public part, and not to the administration sections. Personally, the module comes in handy to avoid duplicates in the public theme, but in the administration section I miss those fields.

Thank you first of all for your work and excuse my English. Greetings.

**Comment by alfonsomontejo** [comment]
I just tested the latest version 1.3.0 and discovered the new option "Show all properties on admin". Really appreciated, thank you!

**Comment by zerocrates** [comment]
Glad you noticed the new release: that's really all that's in it.

I should note that the actual feature was contributed by @Daniel-KM in a pull request not long before you posted this issue (#2).
